# The upstream minikube container is using expired OpenSUSE keys.
# This fetches the updated keys to enable updating packages.
# This is copied from the containerd-shim-spin project: https://github.com/spinframework/containerd-shim-spin/pull/289/commits/cc2e3de2a38935b50940b909707ffcaf42d3769e
FROM gcr.io/k8s-minikube/kicbase:v0.0.46@sha256:fd2d445ddcc33ebc5c6b68a17e6219ea207ce63c005095ea1525296da2d1a279

RUN apt-get update -y || true && \
    apt-get -y install wget curl apt-transport-https ca-certificates gnupg2 && \
    # Remove existing repository configurations to avoid conflicts
    rm -f /etc/apt/sources.list.d/devel:kubic:*.list && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL "https://downloadcontent.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key" | gpg --dearmor > /etc/apt/keyrings/libcontainers-stable.gpg && \
    curl -fsSL "https://downloadcontent.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_22.04/Release.key" | gpg --dearmor > /etc/apt/keyrings/crio-stable.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/libcontainers-stable.gpg] https://downloadcontent.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /" > /etc/apt/sources.list.d/devel-kubic-libcontainers-stable.list && \
    echo "deb [signed-by=/etc/apt/keyrings/crio-stable.gpg] https://downloadcontent.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_22.04/ /" > /etc/apt/sources.list.d/devel-kubic-libcontainers-crio-stable.list && \
    apt-get update -y || true 