name: Helm Chart Smoketest

on:
  workflow_call:

env:
  SPIN_OPERATOR_VERSION: 0.3.0


jobs:
  helm-install-smoke-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install helm
        uses: Azure/setup-helm@v4
        with:
          version: v3.15.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build RCM
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            runtime-class-manager:latest

      - name: Build node installer
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./images/installer/Dockerfile
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            node-installer:latest

      - name: Build shim downloader
        uses: docker/build-push-action@v6
        with:
          context: ./images/downloader
          file: ./images/downloader/Dockerfile
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            shim-downloader:latest

      - name: create kind cluster
        uses: helm/kind-action@v1

      - name: import images into kind cluster
        run: |
          kind load docker-image runtime-class-manager:latest
          kind load docker-image node-installer:latest
          kind load docker-image shim-downloader:latest

      - name: helm install runtime-class-manager
        run: |
          helm install rcm \
            --namespace rcm \
            --create-namespace \
            --debug \
            --set image.repository=runtime-class-manager \
            --set image.tag=latest \
            --set rcm.nodeInstallerImage.repository=node-installer \
            --set rcm.nodeInstallerImage.tag=latest \
            --set rcm.shimDownloaderImage.repository=shim-downloader \
            --set rcm.shimDownloaderImage.tag=latest \
            deploy/helm

      - name: apply Spin shim
        run: kubectl apply -f config/samples/test_shim_spin.yaml

      - name: label nodes
        run: kubectl label node --all spin=true

      - name: run Spin App
        run: |
          kubectl apply -f testdata/apps/spin-app.yaml
          kubectl rollout status deployment wasm-spin --timeout 90s
          kubectl get pods -A
          kubectl port-forward svc/wasm-spin 8083:80 &
          timeout 15s bash -c 'until curl -f -vvv http://localhost:8083/hello; do sleep 2; done'

      - name: debug
        if: failure()
        run: |
          kubectl get pods -A
          kubectl describe shim spin-v2
          kubectl describe runtimeclass wasmtime-spin-v2
          kubectl logs -n rcm -l app.kubernetes.io/name=runtime-class-manager || true
          kubectl describe -n rcm pod -l app.kubernetes.io/name=runtime-class-manager || true
          kubectl logs -l app=wasm-spin || true
          kubectl describe pod -l app=wasm-spin || true

      - name: Verify curl
        run: curl localhost:8083/hello
